name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set env as secret
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
          TEST: ${{ vars.TEST }}
        run: |
          import os
          for q in (os.getenv("TEST_SECRET")):
            print(q)
          for q in (os.getenv("TEST")):
            print(q)
        shell: python
